version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: paperless-ai # This should match the service name of your app below
      APP_PORT: 3000      # This matches the internal port of paperlessai service
  paperlessai:
    image: clusterzx/paperless-ai:3.0.7
    container_name: paperless-ai
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data # For persistent app data
