version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: paperless-ai # This should match the service name of your app below
      APP_PORT: 4000      # This matches the internal port of paperlessai service
      PROXY_AUTH_ADD: 'false'
  paperlessai:
    image: clusterzx/paperless-ai:latest
    container_name: paperless-ai 
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data # For persistent app data
