version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:v1.1.0
    container_name: zigbee2mqtt_proxy
    restart: on-failure
    environment:
      # The service name of the app to proxy to
      APP_HOST: zigbee2mqtt_app_1
      # The port the app is listening on
      APP_PORT: 8089

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt_app
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - /run/udev:/run/udev:ro
