services:
  app_proxy:
    # Corrected the image name to the official Umbrel app proxy
    image: getumbrel/umbrel-app-proxy:v2.0.0
    container_name: zigbee2mqtt_app_proxy_1
    restart: on-failure
    environment:
      # The service name of the app to proxy to (must match the container_name below)
      APP_HOST: zigbee2mqtt_app_1
      # The internal port the app's web UI is running on
      APP_PORT: 8089

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt_app_1
    restart: unless-stopped
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - /run/udev:/run/udev:ro
    # !! IMPORTANT !!
    # You MUST update the device path below to match your Zigbee adapter.
    # To find the path, run 'ls -l /dev/serial/by-id/' on your Umbrel device's command line.
    devices:
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230509182440-if00-port0:/dev/ttyACM0
