version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:v1.1.0
    container_name: zigbee2mqtt_app_proxy_1
    restart: on-failure
    environment:
      # The service name of the app to proxy to
      APP_HOST: zigbee2mqtt_app_1
      # The port the app is listening on
      APP_PORT: 8080

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt_app_1
    restart: unless-stopped
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - /run/udev:/run/udev:ro
    # !! IMPORTANT !!
    # You MUST update the device path below to match your Zigbee adapter.
    # To find the correct path, you can run 'ls -l /dev/serial/by-id/' on your host machine.
    devices:
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230509182440-if00-port0:/dev/ttyACM0
