services:
  app_proxy:
    environment:
      APP_HOST: zigbee2mqtt_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/koenkk/zigbee2mqtt:latest@sha256:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      TZ: Australia/Sydney
      ZIGBEE2MQTT_DATA: /app/data
    devices:
      # Update this path to match your Zigbee USB adapter
      # Find your device with: ls -la /dev/serial/by-id/
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230509182440-if00-port0:/dev/ttyACM0
